---
name: release-windows

# yamllint disable-line rule:truthy
on:
  push:
    tags:
      - '*'
  workflow_dispatch:

defaults:
  run:
    shell: cmd

jobs:
  build:
    strategy:
      matrix:
        # https://github.com/actions/virtual-environments/blob/master/images/win/Windows2016-Readme.md
        os: [windows-2016]
      fail-fast: true
    runs-on: ${{ matrix.os }}
    env:
      # yamllint disable-line rule:line-length
      DEVENV_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\devenv.com
      SLN_PATH: CUETools\CUETools.sln
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      # nasm is required for building Release|Win32
      - uses: ilammy/setup-nasm@v1
      - name: Apply patches
        # yamllint disable-line rule:line-length
        run: |
          git apply --directory=ThirdParty/flac ThirdParty/submodule_flac_CUETools.patch --verbose
          git apply --directory=ThirdParty/WavPack ThirdParty/submodule_WavPack_CUETools_VS2017.patch --verbose
      - name: Build Release|Any CPU
        run: |
          "%DEVENV_PATH%" "%SLN_PATH%" /Build "Release|Any CPU"
      - name: Build Release|x64
        run: |
          "%DEVENV_PATH%" "%SLN_PATH%" /Build "Release|x64"
      - name: Build Release|Win32
        run: |
          "%DEVENV_PATH%" "%SLN_PATH%" /Build "Release|Win32"
      - name: Collect files
        run: |
          CUETools\collect_files.bat
      - uses: actions/upload-artifact@v2
        with:
          name: deploy
          path: bin/Release/CUETools_*/
