---
name: release-windows

# yamllint disable-line rule:truthy
on:
  push:
    tags:
      - '*'
  workflow_dispatch:

defaults:
  run:
    shell: cmd

jobs:
  build:
    strategy:
      matrix:
        # https://github.com/actions/virtual-environments/blob/master/images/win/Windows2022-Readme.md
        os: [windows-2022]
      fail-fast: true
    runs-on: ${{ matrix.os }}
    env:
      # yamllint disable-line rule:line-length
      DEVENV_PATH: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.com
      MSBUILD_PATH: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe
      SLN_PATH: CUETools.sln
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Inno Setup
        run: pwsh -File ./install_inno.ps1
      - name: Apply patches
        # yamllint disable-line rule:line-length
        run: |
          git apply --directory=ThirdParty/flac ThirdParty/submodule_flac_CUETools.patch --verbose --whitespace=nowarn
          powershell -c "Expand-Archive ThirdParty/MAC_SDK/MAC_1086_SDK.zip -DestinationPath ThirdParty/MAC_SDK/"
          git apply --directory=ThirdParty/MAC_SDK ThirdParty/ThirdParty_MAC_SDK_CUETools.patch --verbose
          git apply --directory=ThirdParty/taglib-sharp ThirdParty/submodule_taglib-sharp_CUETools.patch --verbose
          git apply --directory=ThirdParty/WavPack ThirdParty/submodule_WavPack_CUETools.patch --verbose
          git apply --directory=ThirdParty/WindowsMediaLib ThirdParty/submodule_WindowsMediaLib_CUETools.patch --verbose
      - name: MSBuild NuGet restore
        run: |
          "%MSBUILD_PATH%" "%SLN_PATH%" -t:restore -p:Configuration=Release
      - name: Build Release|Any CPU
        run: |
          "%DEVENV_PATH%" "%SLN_PATH%" /Build "Release|Any CPU"
      - name: Build Release|x64
        run: |
          "%DEVENV_PATH%" "%SLN_PATH%" /Build "Release|x64"
      - name: Build Release|Win32
        run: |
          "%DEVENV_PATH%" "%SLN_PATH%" /Build "Release|Win32"
      - name: Collect files
        run: |
          collect_files.bat
      - name: Collect files (Lite)
        run: |
          collect_files_lite.bat
      - name: Package files
        run: pwsh -File ./packaging.ps1
      - name: Get CUETools Version
        id: get_version
        run: |
          for /f "tokens=6 delims= " %%a in ('find "CUEToolsVersion =" .\CUETools.Processor\CUESheet.cs') do set PRODUCTVER=%%a
          set PRODUCTVER=%PRODUCTVER:"=%
          set PRODUCTVER=%PRODUCTVER:;=%
          echo CUETools version: %PRODUCTVER%
          echo CUETOOLS_VERSION=%PRODUCTVER%>>%GITHUB_ENV%
        shell: cmd
      - name: Build Windows installer
        run: |
          "C:\\Program Files (x86)\\Inno Setup 6\\ISCC.exe" "installer.iss"
        shell: cmd
      - name: Generate hash for Windows installer
        run: |
          $installer = "CUETools_Setup_${{ env.CUETOOLS_VERSION }}.exe"
          $installerHash = (Get-FileHash $installer -Algorithm SHA256).Hash.ToLower()
          "$installerHash *$installer" | Out-File -Encoding ASCII "$installer.sha256"
        shell: pwsh
      - name: Add artifacts to Release
        uses: softprops/action-gh-release@v2
        with:
          name: CUETools ${{ env.CUETOOLS_VERSION }}
          body_path: CHANGELOG.md
          draft: false
          prerelease: false
          tag_name: ${{ github.ref_name }}
          files: |
            CUETools_Setup_${{ env.CUETOOLS_VERSION }}.exe
            CUETools_Setup_${{ env.CUETOOLS_VERSION }}.exe.sha256
            CUETools_${{ env.CUETOOLS_VERSION }}.zip
            CUETools_${{ env.CUETOOLS_VERSION }}.zip.sha256
            CUETools.Lite_${{ env.CUETOOLS_VERSION }}.zip
            CUETools.Lite_${{ env.CUETOOLS_VERSION }}.zip.sha256
            CUETools.CTDB.EACPlugin.${{ env.CUETOOLS_VERSION }}.zip
            CUETools.CTDB.EACPlugin.${{ env.CUETOOLS_VERSION }}.zip.sha256
